name: Mirroring

on: [ push, delete ]

jobs:
  to_gitlab:
    name: "Mirror to Gitlab"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@git.itm.uni-luebeck.de:arne.matthes/fiware-ndn-adapter.git
          ssh_private_key:
            ${{ secrets.GITLAB_SSH_PRIVATE_KEY }}

